import Hero from "@/components/Store/Hero";
import SearchBox from "@/lib/SearchBox";
import TopProfiles from "../../lib/TopProfiles";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <TopProfiles />
      <div className="w-full flex flex-col gap-6">
        <SearchBox />
        <Hero />
        <div className="w-full pl-20 pr-16">{children}</div>
      </div>
    </>
  );
}
