import "./globals.css";
import Sidebar from "../components/Sidebar/Sidebar";
import ModalContainer from "@/components/ModalContainer/ModalContainer";
import { AppProvider } from "@/context/AppContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <div className="w-full h-full flex">
            <Sidebar />
            <div className="pl-[360px] w-full min-h-screen   pointer-events-none">
              <main className="w-full h-full  flex flex-col bg-[#242424] relative pointer-events-auto">
                {children}
              </main>
            </div>
            <ModalContainer />
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
